from app.prompting.contracts import PromptSpec


PROMPT_REGISTRY: dict[str, PromptSpec] = {
    "setup.generate": PromptSpec(
        prompt_id="setup.generate",
        version="1",
        template_name="generate_setup",
        output_type="json",
        required_vars=("name", "genre", "description", "style", "complexity"),
    ),
    "storyline.generate": PromptSpec(
        prompt_id="storyline.generate",
        version="1",
        template_name="generate_storyline",
        output_type="json",
        required_vars=("name", "genre", "world_building", "characters", "core_concept"),
    ),
    "outline.generate": PromptSpec(
        prompt_id="outline.generate",
        version="1",
        template_name="generate_outline",
        output_type="json",
        required_vars=(
            "name",
            "world_building",
            "characters",
            "core_concept",
            "storyline",
            "total_chapters",
        ),
    ),
    "chapter.generate": PromptSpec(
        prompt_id="chapter.generate",
        version="1",
        template_name="generate_chapter",
        output_type="plain_text",
        required_vars=("chapter_index", "world_building", "characters", "core_concept"),
    ),
    "dialog.hermes": PromptSpec(
        prompt_id="dialog.hermes",
        version="1",
        template_name="chat_hermes",
        output_type="chat",
        required_vars=(
            "project_name",
            "project_genre",
            "project_description",
            "project_phase",
            "project_status",
            "current_words",
            "target_chapters",
            "target_words",
            "completed_items",
            "missing_items",
            "suggested_next_step",
            "world_context",
        ),
    ),
    "dialog.athena": PromptSpec(
        prompt_id="dialog.athena",
        version="1",
        template_name="chat_athena",
        output_type="chat",
        required_vars=(
            "project_name",
            "project_genre",
            "project_description",
            "project_phase",
            "profile_version",
            "world_context",
        ),
    ),
    "dialog.compact": PromptSpec(
        prompt_id="dialog.compact",
        version="1",
        template_name="compact_dialog_context",
        output_type="plain_text",
        required_vars=("project_name", "dialog_lines"),
    ),
    "project.diagnose": PromptSpec(
        prompt_id="project.diagnose",
        version="1",
        template_name="diagnose_project",
        output_type="json",
        required_vars=(
            "current_phase",
            "has_setup",
            "has_storyline",
            "has_outline",
            "has_chapters",
        ),
    ),
}
