"""add style_config to projects

Revision ID: acdb7e6de884
Revises: 05ffa48c7449
Create Date: 2026-04-17 12:58:43.990418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acdb7e6de884'
down_revision: Union[str, None] = '05ffa48c7449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('style_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'style_config')
    # ### end Alembic commands ###
